import { useId, useMemo, useState } from 'react';

// The interactive component catalog. Data comes from src/data/components.json,
// generated by scripts/build-components.mjs from the engine registry — nothing
// here is typed by hand. Astro renders the initial (unfiltered) list at build
// time, so the full catalog is present without JavaScript; search and the
// filters need it.

export interface CatalogComponent {
	ref: string;
	name: string;
	category: string;
	genres: string[];
	tags: string[];
	synonyms: string[];
	description: string;
	archetype: string;
	extends: string;
	entity_type: string;
	sensors: string[];
	affordances: string[];
	latent_affordances: string[];
	failure_modes: string[];
	file: string;
}

export interface CatalogData {
	source_label: string;
	count: number;
	categories: { name: string; count: number }[];
	genres: { name: string; count: number }[];
	components: CatalogComponent[];
}

interface Props {
	data: CatalogData;
	/** Base URL for a component's YAML on GitHub; `file` is appended. */
	sourceBase: string;
}

const ALL = 'all';

function haystack(c: CatalogComponent): string {
	return [
		c.ref,
		c.name.replace(/_/g, ' '),
		c.entity_type,
		c.archetype,
		c.extends,
		...c.genres,
		...c.tags,
		...c.synonyms,
		...c.sensors,
		...c.affordances,
		...c.latent_affordances,
		...c.failure_modes,
		c.description,
	]
		.join(' ')
		.toLowerCase();
}

export default function ComponentCatalog({ data, sourceBase }: Props) {
	const [query, setQuery] = useState('');
	const [category, setCategory] = useState(ALL);
	const [genre, setGenre] = useState(ALL);
	const searchId = useId();
	const categoryId = useId();
	const genreId = useId();

	const indexed = useMemo(
		() => data.components.map((c) => ({ c, text: haystack(c) })),
		[data.components],
	);

	const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
	const visible = indexed
		.filter(({ c, text }) => {
			if (category !== ALL && c.category !== category) return false;
			if (genre !== ALL && !c.genres.includes(genre)) return false;
			return terms.every((t) => text.includes(t));
		})
		.map(({ c }) => c);

	const filtered = query !== '' || category !== ALL || genre !== ALL;

	return (
		<div className="catalog">
			<form className="catalog-controls" role="search" onSubmit={(e) => e.preventDefault()}>
				<div className="catalog-field catalog-field--grow">
					<label htmlFor={searchId}>Search</label>
					<input
						id={searchId}
						type="search"
						value={query}
						onChange={(e) => setQuery(e.target.value)}
						placeholder="name, synonym, sensor, affordance, failure mode…"
						autoComplete="off"
					/>
				</div>
				<div className="catalog-field">
					<label htmlFor={categoryId}>Category</label>
					<select id={categoryId} value={category} onChange={(e) => setCategory(e.target.value)}>
						<option value={ALL}>All ({data.count})</option>
						{data.categories.map((k) => (
							<option key={k.name} value={k.name}>
								{k.name} ({k.count})
							</option>
						))}
					</select>
				</div>
				<div className="catalog-field">
					<label htmlFor={genreId}>Genre</label>
					<select id={genreId} value={genre} onChange={(e) => setGenre(e.target.value)}>
						<option value={ALL}>All</option>
						{data.genres.map((g) => (
							<option key={g.name} value={g.name}>
								{g.name} ({g.count})
							</option>
						))}
					</select>
				</div>
				<div className="catalog-field catalog-field--button">
					<button
						type="button"
						onClick={() => {
							setQuery('');
							setCategory(ALL);
							setGenre(ALL);
						}}
						disabled={!filtered}
					>
						Clear
					</button>
				</div>
			</form>

			<p className="catalog-status" aria-live="polite" aria-atomic="true">
				{filtered
					? `${visible.length} of ${data.count} components match.`
					: `${data.count} components in ${data.categories.length} categories, read from ${data.source_label}.`}
			</p>

			{visible.length === 0 ? (
				<p className="catalog-empty">
					Nothing matches. Synonyms are searched too, so try a plainer word — or clear the filters.
				</p>
			) : (
				<ul className="catalog-list">
					{visible.map((c) => (
						<li key={c.ref} className="catalog-card" id={`c-${c.ref.replace('/', '-')}`}>
							<div className="catalog-card-head">
								<h3>
									<code>{c.ref}</code>
								</h3>
								<span className="catalog-chips" aria-label="genres">
									{c.genres.map((g) => (
										<span key={g} className={`catalog-chip catalog-chip--${g}`}>
											{g}
										</span>
									))}
								</span>
							</div>
							{c.description ? <p className="catalog-desc">{c.description}</p> : null}
							<dl className="catalog-facts">
								{c.entity_type ? (
									<>
										<dt>Entity type</dt>
										<dd>
											<code>{c.entity_type}</code>
											{c.archetype ? (
												<>
													{' · archetype '}
													<code>{c.archetype}</code>
												</>
											) : null}
											{c.extends ? (
												<>
													{' · extends '}
													<code>{c.extends}</code>
												</>
											) : null}
										</dd>
									</>
								) : null}
								<dt>Sensors</dt>
								<dd>{c.sensors.length ? c.sensors.join(', ') : <em>none declared</em>}</dd>
								<dt>Affordances</dt>
								<dd>
									{c.affordances.length ? c.affordances.join(', ') : <em>none declared</em>}
									{c.latent_affordances.length ? (
										<>
											{' — latent: '}
											{c.latent_affordances.join(', ')}
										</>
									) : null}
								</dd>
								<dt>Fails by</dt>
								<dd>{c.failure_modes.length ? c.failure_modes.join(', ') : <em>no failure modes</em>}</dd>
								{c.synonyms.length ? (
									<>
										<dt>Also answers to</dt>
										<dd>{c.synonyms.join(', ')}</dd>
									</>
								) : null}
								{c.tags.length ? (
									<>
										<dt>Tags</dt>
										<dd>{c.tags.join(', ')}</dd>
									</>
								) : null}
							</dl>
							<p className="catalog-source">
								<a href={`${sourceBase}${c.file}`} rel="noopener">
									{c.file}
								</a>
							</p>
						</li>
					))}
				</ul>
			)}
		</div>
	);
}
